name: 'Bump version'
description: 'This action bumps package versions based on the repository's commit messages written according to the Conventional Commits specification.'

runs:
  using: 'composite'
  steps:
    - name: 'Generate changelog'
      shell: bash
      run: cz bump --files-only --yes
