name: Create pull request
description: Create pull request
author: DFINITY Stiftung

inputs:
  branch_name:
    description: 'The name of the branch to create a pull request from.'
    default: 'patch'
  base_branch_name:
    description: 'The name of the base branch to create a pull request against.'
    default: 'main'

  pull_request_title:
    description: 'The title of the pull request.'
    default: 'chore: automated by GitHub actions'
  pull_request_body:
    description: 'The body of the pull request.'
    default: 'This pull request was automatically created by a GitHub Action'

  author_name:
    description: 'The name of the author of the pull request and commit.'
    default: '${{ github.actor }}'
  author_email:
    description: 'The email of the author of the pull request and commit.'
    default: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'

  commit_message:
    description: 'The message of the commit.'
    default: 'chore: automated by GitHub actions'

  token:
    description: 'Access token to manage the pull request.'
    default: '${{ github.token }}'

outputs:
  pull_request_number:
    description: 'The number of the created pull request.'

runs:
  using: node20
  main: dist/index.js
